/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-30 at 04:15:50 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for ClientVersionMatch.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ClientVersionMatch extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String approvedAndroidClientVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String approvedIOSClientVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String serverVersion;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getApprovedAndroidClientVersion() {
    return approvedAndroidClientVersion;
  }

  /**
   * @param approvedAndroidClientVersion approvedAndroidClientVersion or {@code null} for none
   */
  public ClientVersionMatch setApprovedAndroidClientVersion(java.lang.String approvedAndroidClientVersion) {
    this.approvedAndroidClientVersion = approvedAndroidClientVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getApprovedIOSClientVersion() {
    return approvedIOSClientVersion;
  }

  /**
   * @param approvedIOSClientVersion approvedIOSClientVersion or {@code null} for none
   */
  public ClientVersionMatch setApprovedIOSClientVersion(java.lang.String approvedIOSClientVersion) {
    this.approvedIOSClientVersion = approvedIOSClientVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public ClientVersionMatch setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getServerVersion() {
    return serverVersion;
  }

  /**
   * @param serverVersion serverVersion or {@code null} for none
   */
  public ClientVersionMatch setServerVersion(java.lang.String serverVersion) {
    this.serverVersion = serverVersion;
    return this;
  }

  @Override
  public ClientVersionMatch set(String fieldName, Object value) {
    return (ClientVersionMatch) super.set(fieldName, value);
  }

  @Override
  public ClientVersionMatch clone() {
    return (ClientVersionMatch) super.clone();
  }

}
