/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-20 at 19:47:10 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for MenuItemAndStats.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MenuItemAndStats extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private StoreMenuItem menuItem;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private StoreItemStats stats;

  /**
   * @return value or {@code null} for none
   */
  public StoreMenuItem getMenuItem() {
    return menuItem;
  }

  /**
   * @param menuItem menuItem or {@code null} for none
   */
  public MenuItemAndStats setMenuItem(StoreMenuItem menuItem) {
    this.menuItem = menuItem;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public StoreItemStats getStats() {
    return stats;
  }

  /**
   * @param stats stats or {@code null} for none
   */
  public MenuItemAndStats setStats(StoreItemStats stats) {
    this.stats = stats;
    return this;
  }

  @Override
  public MenuItemAndStats set(String fieldName, Object value) {
    return (MenuItemAndStats) super.set(fieldName, value);
  }

  @Override
  public MenuItemAndStats clone() {
    return (MenuItemAndStats) super.clone();
  }

}
