/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-07 at 04:40:21 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for MenusAndMenuItems.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MenusAndMenuItems extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MenuItemAndStats> menuItems;

  static {
    // hack to force ProGuard to consider MenuItemAndStats used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(MenuItemAndStats.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<StoreMenuStats> menuStats;

  static {
    // hack to force ProGuard to consider StoreMenuStats used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(StoreMenuStats.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<StoreMenuHierarchy> menusAndSubmenus;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MenuItemAndStats> getMenuItems() {
    return menuItems;
  }

  /**
   * @param menuItems menuItems or {@code null} for none
   */
  public MenusAndMenuItems setMenuItems(java.util.List<MenuItemAndStats> menuItems) {
    this.menuItems = menuItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<StoreMenuStats> getMenuStats() {
    return menuStats;
  }

  /**
   * @param menuStats menuStats or {@code null} for none
   */
  public MenusAndMenuItems setMenuStats(java.util.List<StoreMenuStats> menuStats) {
    this.menuStats = menuStats;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<StoreMenuHierarchy> getMenusAndSubmenus() {
    return menusAndSubmenus;
  }

  /**
   * @param menusAndSubmenus menusAndSubmenus or {@code null} for none
   */
  public MenusAndMenuItems setMenusAndSubmenus(java.util.List<StoreMenuHierarchy> menusAndSubmenus) {
    this.menusAndSubmenus = menusAndSubmenus;
    return this;
  }

  @Override
  public MenusAndMenuItems set(String fieldName, Object value) {
    return (MenusAndMenuItems) super.set(fieldName, value);
  }

  @Override
  public MenusAndMenuItems clone() {
    return (MenusAndMenuItems) super.clone();
  }

}
