/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-25 at 14:38:01 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for OrderItem.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class OrderItem extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long finalPrice;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long initialPrice;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long menuItemId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long menuItemName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifiedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long orderId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long posOrderItemId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long quantity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String selectedOptions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String specialInstructions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedDate() {
    return createdDate;
  }

  /**
   * @param createdDate createdDate or {@code null} for none
   */
  public OrderItem setCreatedDate(java.lang.Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public OrderItem setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFinalPrice() {
    return finalPrice;
  }

  /**
   * @param finalPrice finalPrice or {@code null} for none
   */
  public OrderItem setFinalPrice(java.lang.Long finalPrice) {
    this.finalPrice = finalPrice;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public OrderItem setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getInitialPrice() {
    return initialPrice;
  }

  /**
   * @param initialPrice initialPrice or {@code null} for none
   */
  public OrderItem setInitialPrice(java.lang.Long initialPrice) {
    this.initialPrice = initialPrice;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMenuItemId() {
    return menuItemId;
  }

  /**
   * @param menuItemId menuItemId or {@code null} for none
   */
  public OrderItem setMenuItemId(java.lang.Long menuItemId) {
    this.menuItemId = menuItemId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMenuItemName() {
    return menuItemName;
  }

  /**
   * @param menuItemName menuItemName or {@code null} for none
   */
  public OrderItem setMenuItemName(java.lang.Long menuItemName) {
    this.menuItemName = menuItemName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifiedDate() {
    return modifiedDate;
  }

  /**
   * @param modifiedDate modifiedDate or {@code null} for none
   */
  public OrderItem setModifiedDate(java.lang.Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOrderId() {
    return orderId;
  }

  /**
   * @param orderId orderId or {@code null} for none
   */
  public OrderItem setOrderId(java.lang.Long orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPosOrderItemId() {
    return posOrderItemId;
  }

  /**
   * @param posOrderItemId posOrderItemId or {@code null} for none
   */
  public OrderItem setPosOrderItemId(java.lang.Long posOrderItemId) {
    this.posOrderItemId = posOrderItemId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getQuantity() {
    return quantity;
  }

  /**
   * @param quantity quantity or {@code null} for none
   */
  public OrderItem setQuantity(java.lang.Long quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSelectedOptions() {
    return selectedOptions;
  }

  /**
   * @param selectedOptions selectedOptions or {@code null} for none
   */
  public OrderItem setSelectedOptions(java.lang.String selectedOptions) {
    this.selectedOptions = selectedOptions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSpecialInstructions() {
    return specialInstructions;
  }

  /**
   * @param specialInstructions specialInstructions or {@code null} for none
   */
  public OrderItem setSpecialInstructions(java.lang.String specialInstructions) {
    this.specialInstructions = specialInstructions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * @param storeId storeId or {@code null} for none
   */
  public OrderItem setStoreId(java.lang.Long storeId) {
    this.storeId = storeId;
    return this;
  }

  @Override
  public OrderItem set(String fieldName, Object value) {
    return (OrderItem) super.set(fieldName, value);
  }

  @Override
  public OrderItem clone() {
    return (OrderItem) super.clone();
  }

}
