/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-25 at 14:38:01 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for OrderItemsAndCustomers.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class OrderItemsAndCustomers extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Order order;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<OrderCustomer> orderCustomers;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<OrderItem> orderItems;

  /**
   * @return value or {@code null} for none
   */
  public Order getOrder() {
    return order;
  }

  /**
   * @param order order or {@code null} for none
   */
  public OrderItemsAndCustomers setOrder(Order order) {
    this.order = order;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<OrderCustomer> getOrderCustomers() {
    return orderCustomers;
  }

  /**
   * @param orderCustomers orderCustomers or {@code null} for none
   */
  public OrderItemsAndCustomers setOrderCustomers(java.util.List<OrderCustomer> orderCustomers) {
    this.orderCustomers = orderCustomers;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<OrderItem> getOrderItems() {
    return orderItems;
  }

  /**
   * @param orderItems orderItems or {@code null} for none
   */
  public OrderItemsAndCustomers setOrderItems(java.util.List<OrderItem> orderItems) {
    this.orderItems = orderItems;
    return this;
  }

  @Override
  public OrderItemsAndCustomers set(String fieldName, Object value) {
    return (OrderItemsAndCustomers) super.set(fieldName, value);
  }

  @Override
  public OrderItemsAndCustomers clone() {
    return (OrderItemsAndCustomers) super.clone();
  }

}
