/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-25 at 14:38:01 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for Order.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Order extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long closeDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long discount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String discountDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gratuity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long invoiceNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifiedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String paymentApprovalToken;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String paymentProvider;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String paymentType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long poscheckId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String serverFirstName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String serverLastName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long serverPOSId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long serviceCharge;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long tax;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long totalAmount;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCloseDate() {
    return closeDate;
  }

  /**
   * @param closeDate closeDate or {@code null} for none
   */
  public Order setCloseDate(java.lang.Long closeDate) {
    this.closeDate = closeDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedDate() {
    return createdDate;
  }

  /**
   * @param createdDate createdDate or {@code null} for none
   */
  public Order setCreatedDate(java.lang.Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getDiscount() {
    return discount;
  }

  /**
   * @param discount discount or {@code null} for none
   */
  public Order setDiscount(java.lang.Long discount) {
    this.discount = discount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDiscountDescription() {
    return discountDescription;
  }

  /**
   * @param discountDescription discountDescription or {@code null} for none
   */
  public Order setDiscountDescription(java.lang.String discountDescription) {
    this.discountDescription = discountDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGratuity() {
    return gratuity;
  }

  /**
   * @param gratuity gratuity or {@code null} for none
   */
  public Order setGratuity(java.lang.Long gratuity) {
    this.gratuity = gratuity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Order setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getInvoiceNumber() {
    return invoiceNumber;
  }

  /**
   * @param invoiceNumber invoiceNumber or {@code null} for none
   */
  public Order setInvoiceNumber(java.lang.Long invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifiedDate() {
    return modifiedDate;
  }

  /**
   * @param modifiedDate modifiedDate or {@code null} for none
   */
  public Order setModifiedDate(java.lang.Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPaymentApprovalToken() {
    return paymentApprovalToken;
  }

  /**
   * @param paymentApprovalToken paymentApprovalToken or {@code null} for none
   */
  public Order setPaymentApprovalToken(java.lang.String paymentApprovalToken) {
    this.paymentApprovalToken = paymentApprovalToken;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPaymentProvider() {
    return paymentProvider;
  }

  /**
   * @param paymentProvider paymentProvider or {@code null} for none
   */
  public Order setPaymentProvider(java.lang.String paymentProvider) {
    this.paymentProvider = paymentProvider;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPaymentType() {
    return paymentType;
  }

  /**
   * @param paymentType paymentType or {@code null} for none
   */
  public Order setPaymentType(java.lang.String paymentType) {
    this.paymentType = paymentType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPoscheckId() {
    return poscheckId;
  }

  /**
   * @param poscheckId poscheckId or {@code null} for none
   */
  public Order setPoscheckId(java.lang.Long poscheckId) {
    this.poscheckId = poscheckId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getServerFirstName() {
    return serverFirstName;
  }

  /**
   * @param serverFirstName serverFirstName or {@code null} for none
   */
  public Order setServerFirstName(java.lang.String serverFirstName) {
    this.serverFirstName = serverFirstName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getServerLastName() {
    return serverLastName;
  }

  /**
   * @param serverLastName serverLastName or {@code null} for none
   */
  public Order setServerLastName(java.lang.String serverLastName) {
    this.serverLastName = serverLastName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getServerPOSId() {
    return serverPOSId;
  }

  /**
   * @param serverPOSId serverPOSId or {@code null} for none
   */
  public Order setServerPOSId(java.lang.Long serverPOSId) {
    this.serverPOSId = serverPOSId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getServiceCharge() {
    return serviceCharge;
  }

  /**
   * @param serviceCharge serviceCharge or {@code null} for none
   */
  public Order setServiceCharge(java.lang.Long serviceCharge) {
    this.serviceCharge = serviceCharge;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public Order setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * @param storeId storeId or {@code null} for none
   */
  public Order setStoreId(java.lang.Long storeId) {
    this.storeId = storeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTax() {
    return tax;
  }

  /**
   * @param tax tax or {@code null} for none
   */
  public Order setTax(java.lang.Long tax) {
    this.tax = tax;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTotalAmount() {
    return totalAmount;
  }

  /**
   * @param totalAmount totalAmount or {@code null} for none
   */
  public Order setTotalAmount(java.lang.Long totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

  @Override
  public Order set(String fieldName, Object value) {
    return (Order) super.set(fieldName, value);
  }

  @Override
  public Order clone() {
    return (Order) super.clone();
  }

}
