/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-28 at 02:45:33 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for StorePOSConnection.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StorePOSConnection extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long asaanTenderId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long carryoutModeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long deliveryModeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String hiddenHeaderName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String hiddenHeaderValue;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifiedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String token;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String url;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getAsaanTenderId() {
    return asaanTenderId;
  }

  /**
   * @param asaanTenderId asaanTenderId or {@code null} for none
   */
  public StorePOSConnection setAsaanTenderId(java.lang.Long asaanTenderId) {
    this.asaanTenderId = asaanTenderId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCarryoutModeId() {
    return carryoutModeId;
  }

  /**
   * @param carryoutModeId carryoutModeId or {@code null} for none
   */
  public StorePOSConnection setCarryoutModeId(java.lang.Long carryoutModeId) {
    this.carryoutModeId = carryoutModeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedDate() {
    return createdDate;
  }

  /**
   * @param createdDate createdDate or {@code null} for none
   */
  public StorePOSConnection setCreatedDate(java.lang.Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getDeliveryModeId() {
    return deliveryModeId;
  }

  /**
   * @param deliveryModeId deliveryModeId or {@code null} for none
   */
  public StorePOSConnection setDeliveryModeId(java.lang.Long deliveryModeId) {
    this.deliveryModeId = deliveryModeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHiddenHeaderName() {
    return hiddenHeaderName;
  }

  /**
   * @param hiddenHeaderName hiddenHeaderName or {@code null} for none
   */
  public StorePOSConnection setHiddenHeaderName(java.lang.String hiddenHeaderName) {
    this.hiddenHeaderName = hiddenHeaderName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHiddenHeaderValue() {
    return hiddenHeaderValue;
  }

  /**
   * @param hiddenHeaderValue hiddenHeaderValue or {@code null} for none
   */
  public StorePOSConnection setHiddenHeaderValue(java.lang.String hiddenHeaderValue) {
    this.hiddenHeaderValue = hiddenHeaderValue;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifiedDate() {
    return modifiedDate;
  }

  /**
   * @param modifiedDate modifiedDate or {@code null} for none
   */
  public StorePOSConnection setModifiedDate(java.lang.Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public StorePOSConnection setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * @param storeId storeId or {@code null} for none
   */
  public StorePOSConnection setStoreId(java.lang.Long storeId) {
    this.storeId = storeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getToken() {
    return token;
  }

  /**
   * @param token token or {@code null} for none
   */
  public StorePOSConnection setToken(java.lang.String token) {
    this.token = token;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * @param url url or {@code null} for none
   */
  public StorePOSConnection setUrl(java.lang.String url) {
    this.url = url;
    return this;
  }

  @Override
  public StorePOSConnection set(String fieldName, Object value) {
    return (StorePOSConnection) super.set(fieldName, value);
  }

  @Override
  public StorePOSConnection clone() {
    return (StorePOSConnection) super.clone();
  }

}
