/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-30 at 04:15:50 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for StoreWaitlistSummary.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreWaitlistSummary extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifiedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("partiesOfSize1_2")
  private java.lang.Integer partiesOfSize12;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("partiesOfSize3_4")
  private java.lang.Integer partiesOfSize34;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer partiesOfSize5OrMore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("waitTime1_2")
  private java.lang.String waitTime12;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("waitTime3_4")
  private java.lang.String waitTime34;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String waitTime5OrMore;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedDate() {
    return createdDate;
  }

  /**
   * @param createdDate createdDate or {@code null} for none
   */
  public StoreWaitlistSummary setCreatedDate(java.lang.Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifiedDate() {
    return modifiedDate;
  }

  /**
   * @param modifiedDate modifiedDate or {@code null} for none
   */
  public StoreWaitlistSummary setModifiedDate(java.lang.Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPartiesOfSize12() {
    return partiesOfSize12;
  }

  /**
   * @param partiesOfSize12 partiesOfSize12 or {@code null} for none
   */
  public StoreWaitlistSummary setPartiesOfSize12(java.lang.Integer partiesOfSize12) {
    this.partiesOfSize12 = partiesOfSize12;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPartiesOfSize34() {
    return partiesOfSize34;
  }

  /**
   * @param partiesOfSize34 partiesOfSize34 or {@code null} for none
   */
  public StoreWaitlistSummary setPartiesOfSize34(java.lang.Integer partiesOfSize34) {
    this.partiesOfSize34 = partiesOfSize34;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPartiesOfSize5OrMore() {
    return partiesOfSize5OrMore;
  }

  /**
   * @param partiesOfSize5OrMore partiesOfSize5OrMore or {@code null} for none
   */
  public StoreWaitlistSummary setPartiesOfSize5OrMore(java.lang.Integer partiesOfSize5OrMore) {
    this.partiesOfSize5OrMore = partiesOfSize5OrMore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * @param storeId storeId or {@code null} for none
   */
  public StoreWaitlistSummary setStoreId(java.lang.Long storeId) {
    this.storeId = storeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWaitTime12() {
    return waitTime12;
  }

  /**
   * @param waitTime12 waitTime12 or {@code null} for none
   */
  public StoreWaitlistSummary setWaitTime12(java.lang.String waitTime12) {
    this.waitTime12 = waitTime12;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWaitTime34() {
    return waitTime34;
  }

  /**
   * @param waitTime34 waitTime34 or {@code null} for none
   */
  public StoreWaitlistSummary setWaitTime34(java.lang.String waitTime34) {
    this.waitTime34 = waitTime34;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWaitTime5OrMore() {
    return waitTime5OrMore;
  }

  /**
   * @param waitTime5OrMore waitTime5OrMore or {@code null} for none
   */
  public StoreWaitlistSummary setWaitTime5OrMore(java.lang.String waitTime5OrMore) {
    this.waitTime5OrMore = waitTime5OrMore;
    return this;
  }

  @Override
  public StoreWaitlistSummary set(String fieldName, Object value) {
    return (StoreWaitlistSummary) super.set(fieldName, value);
  }

  @Override
  public StoreWaitlistSummary clone() {
    return (StoreWaitlistSummary) super.clone();
  }

}
