/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-30 at 04:15:50 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for StoreMenuItemModifierGroup.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreMenuItemModifierGroup extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer menuItemPOSId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifiedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String modifierGroupLongDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer modifierGroupMaximum;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer modifierGroupMinimum;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer modifierGroupPOSId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String modifierGroupShortDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedDate() {
    return createdDate;
  }

  /**
   * @param createdDate createdDate or {@code null} for none
   */
  public StoreMenuItemModifierGroup setCreatedDate(java.lang.Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public StoreMenuItemModifierGroup setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMenuItemPOSId() {
    return menuItemPOSId;
  }

  /**
   * @param menuItemPOSId menuItemPOSId or {@code null} for none
   */
  public StoreMenuItemModifierGroup setMenuItemPOSId(java.lang.Integer menuItemPOSId) {
    this.menuItemPOSId = menuItemPOSId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifiedDate() {
    return modifiedDate;
  }

  /**
   * @param modifiedDate modifiedDate or {@code null} for none
   */
  public StoreMenuItemModifierGroup setModifiedDate(java.lang.Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModifierGroupLongDescription() {
    return modifierGroupLongDescription;
  }

  /**
   * @param modifierGroupLongDescription modifierGroupLongDescription or {@code null} for none
   */
  public StoreMenuItemModifierGroup setModifierGroupLongDescription(java.lang.String modifierGroupLongDescription) {
    this.modifierGroupLongDescription = modifierGroupLongDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getModifierGroupMaximum() {
    return modifierGroupMaximum;
  }

  /**
   * @param modifierGroupMaximum modifierGroupMaximum or {@code null} for none
   */
  public StoreMenuItemModifierGroup setModifierGroupMaximum(java.lang.Integer modifierGroupMaximum) {
    this.modifierGroupMaximum = modifierGroupMaximum;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getModifierGroupMinimum() {
    return modifierGroupMinimum;
  }

  /**
   * @param modifierGroupMinimum modifierGroupMinimum or {@code null} for none
   */
  public StoreMenuItemModifierGroup setModifierGroupMinimum(java.lang.Integer modifierGroupMinimum) {
    this.modifierGroupMinimum = modifierGroupMinimum;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getModifierGroupPOSId() {
    return modifierGroupPOSId;
  }

  /**
   * @param modifierGroupPOSId modifierGroupPOSId or {@code null} for none
   */
  public StoreMenuItemModifierGroup setModifierGroupPOSId(java.lang.Integer modifierGroupPOSId) {
    this.modifierGroupPOSId = modifierGroupPOSId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModifierGroupShortDescription() {
    return modifierGroupShortDescription;
  }

  /**
   * @param modifierGroupShortDescription modifierGroupShortDescription or {@code null} for none
   */
  public StoreMenuItemModifierGroup setModifierGroupShortDescription(java.lang.String modifierGroupShortDescription) {
    this.modifierGroupShortDescription = modifierGroupShortDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * @param storeId storeId or {@code null} for none
   */
  public StoreMenuItemModifierGroup setStoreId(java.lang.Long storeId) {
    this.storeId = storeId;
    return this;
  }

  @Override
  public StoreMenuItemModifierGroup set(String fieldName, Object value) {
    return (StoreMenuItemModifierGroup) super.set(fieldName, value);
  }

  @Override
  public StoreMenuItemModifierGroup clone() {
    return (StoreMenuItemModifierGroup) super.clone();
  }

}
