/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-07 at 04:40:21 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for StoreTableGroupMember.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreTableGroupMember extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long finalTotal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String firstName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lastName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifiedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long orderId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String paidItems;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer payingFor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long payingUserId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String paymentChargeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String paymentInvoice;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String paymentReceiptNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer paymentType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profilePhotoUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeTableGroupId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long subtotal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long tax;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long tip;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedDate() {
    return createdDate;
  }

  /**
   * @param createdDate createdDate or {@code null} for none
   */
  public StoreTableGroupMember setCreatedDate(java.lang.Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFinalTotal() {
    return finalTotal;
  }

  /**
   * @param finalTotal finalTotal or {@code null} for none
   */
  public StoreTableGroupMember setFinalTotal(java.lang.Long finalTotal) {
    this.finalTotal = finalTotal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFirstName() {
    return firstName;
  }

  /**
   * @param firstName firstName or {@code null} for none
   */
  public StoreTableGroupMember setFirstName(java.lang.String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public StoreTableGroupMember setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastName() {
    return lastName;
  }

  /**
   * @param lastName lastName or {@code null} for none
   */
  public StoreTableGroupMember setLastName(java.lang.String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifiedDate() {
    return modifiedDate;
  }

  /**
   * @param modifiedDate modifiedDate or {@code null} for none
   */
  public StoreTableGroupMember setModifiedDate(java.lang.Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOrderId() {
    return orderId;
  }

  /**
   * @param orderId orderId or {@code null} for none
   */
  public StoreTableGroupMember setOrderId(java.lang.Long orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPaidItems() {
    return paidItems;
  }

  /**
   * @param paidItems paidItems or {@code null} for none
   */
  public StoreTableGroupMember setPaidItems(java.lang.String paidItems) {
    this.paidItems = paidItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPayingFor() {
    return payingFor;
  }

  /**
   * @param payingFor payingFor or {@code null} for none
   */
  public StoreTableGroupMember setPayingFor(java.lang.Integer payingFor) {
    this.payingFor = payingFor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPayingUserId() {
    return payingUserId;
  }

  /**
   * @param payingUserId payingUserId or {@code null} for none
   */
  public StoreTableGroupMember setPayingUserId(java.lang.Long payingUserId) {
    this.payingUserId = payingUserId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPaymentChargeId() {
    return paymentChargeId;
  }

  /**
   * @param paymentChargeId paymentChargeId or {@code null} for none
   */
  public StoreTableGroupMember setPaymentChargeId(java.lang.String paymentChargeId) {
    this.paymentChargeId = paymentChargeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPaymentInvoice() {
    return paymentInvoice;
  }

  /**
   * @param paymentInvoice paymentInvoice or {@code null} for none
   */
  public StoreTableGroupMember setPaymentInvoice(java.lang.String paymentInvoice) {
    this.paymentInvoice = paymentInvoice;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPaymentReceiptNumber() {
    return paymentReceiptNumber;
  }

  /**
   * @param paymentReceiptNumber paymentReceiptNumber or {@code null} for none
   */
  public StoreTableGroupMember setPaymentReceiptNumber(java.lang.String paymentReceiptNumber) {
    this.paymentReceiptNumber = paymentReceiptNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPaymentType() {
    return paymentType;
  }

  /**
   * @param paymentType paymentType or {@code null} for none
   */
  public StoreTableGroupMember setPaymentType(java.lang.Integer paymentType) {
    this.paymentType = paymentType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfilePhotoUrl() {
    return profilePhotoUrl;
  }

  /**
   * @param profilePhotoUrl profilePhotoUrl or {@code null} for none
   */
  public StoreTableGroupMember setProfilePhotoUrl(java.lang.String profilePhotoUrl) {
    this.profilePhotoUrl = profilePhotoUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreTableGroupId() {
    return storeTableGroupId;
  }

  /**
   * @param storeTableGroupId storeTableGroupId or {@code null} for none
   */
  public StoreTableGroupMember setStoreTableGroupId(java.lang.Long storeTableGroupId) {
    this.storeTableGroupId = storeTableGroupId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSubtotal() {
    return subtotal;
  }

  /**
   * @param subtotal subtotal or {@code null} for none
   */
  public StoreTableGroupMember setSubtotal(java.lang.Long subtotal) {
    this.subtotal = subtotal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTax() {
    return tax;
  }

  /**
   * @param tax tax or {@code null} for none
   */
  public StoreTableGroupMember setTax(java.lang.Long tax) {
    this.tax = tax;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTip() {
    return tip;
  }

  /**
   * @param tip tip or {@code null} for none
   */
  public StoreTableGroupMember setTip(java.lang.Long tip) {
    this.tip = tip;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public StoreTableGroupMember setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public StoreTableGroupMember set(String fieldName, Object value) {
    return (StoreTableGroupMember) super.set(fieldName, value);
  }

  @Override
  public StoreTableGroupMember clone() {
    return (StoreTableGroupMember) super.clone();
  }

}
