/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-30 at 04:15:50 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for StoreOrderAndTeamDetails.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreOrderAndTeamDetails extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private StoreTableGroupMember memberMe;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<StoreTableGroupMember> members;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private StoreOrder order;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Store store;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private StoreTableGroup storeTableGroup;

  /**
   * @return value or {@code null} for none
   */
  public StoreTableGroupMember getMemberMe() {
    return memberMe;
  }

  /**
   * @param memberMe memberMe or {@code null} for none
   */
  public StoreOrderAndTeamDetails setMemberMe(StoreTableGroupMember memberMe) {
    this.memberMe = memberMe;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<StoreTableGroupMember> getMembers() {
    return members;
  }

  /**
   * @param members members or {@code null} for none
   */
  public StoreOrderAndTeamDetails setMembers(java.util.List<StoreTableGroupMember> members) {
    this.members = members;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public StoreOrder getOrder() {
    return order;
  }

  /**
   * @param order order or {@code null} for none
   */
  public StoreOrderAndTeamDetails setOrder(StoreOrder order) {
    this.order = order;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Store getStore() {
    return store;
  }

  /**
   * @param store store or {@code null} for none
   */
  public StoreOrderAndTeamDetails setStore(Store store) {
    this.store = store;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public StoreTableGroup getStoreTableGroup() {
    return storeTableGroup;
  }

  /**
   * @param storeTableGroup storeTableGroup or {@code null} for none
   */
  public StoreOrderAndTeamDetails setStoreTableGroup(StoreTableGroup storeTableGroup) {
    this.storeTableGroup = storeTableGroup;
    return this;
  }

  @Override
  public StoreOrderAndTeamDetails set(String fieldName, Object value) {
    return (StoreOrderAndTeamDetails) super.set(fieldName, value);
  }

  @Override
  public StoreOrderAndTeamDetails clone() {
    return (StoreOrderAndTeamDetails) super.clone();
  }

}
