/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-28 at 02:45:33 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for StoreMenuItemModifier.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreMenuItemModifier extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String longDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifiedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String modifierGroupLongDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifierGroupMaximum;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifierGroupMinimum;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifierGroupPOSId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String modifierGroupShortDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifierPOSId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long price;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String shortDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long weighting;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedDate() {
    return createdDate;
  }

  /**
   * @param createdDate createdDate or {@code null} for none
   */
  public StoreMenuItemModifier setCreatedDate(java.lang.Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public StoreMenuItemModifier setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLongDescription() {
    return longDescription;
  }

  /**
   * @param longDescription longDescription or {@code null} for none
   */
  public StoreMenuItemModifier setLongDescription(java.lang.String longDescription) {
    this.longDescription = longDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifiedDate() {
    return modifiedDate;
  }

  /**
   * @param modifiedDate modifiedDate or {@code null} for none
   */
  public StoreMenuItemModifier setModifiedDate(java.lang.Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModifierGroupLongDescription() {
    return modifierGroupLongDescription;
  }

  /**
   * @param modifierGroupLongDescription modifierGroupLongDescription or {@code null} for none
   */
  public StoreMenuItemModifier setModifierGroupLongDescription(java.lang.String modifierGroupLongDescription) {
    this.modifierGroupLongDescription = modifierGroupLongDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifierGroupMaximum() {
    return modifierGroupMaximum;
  }

  /**
   * @param modifierGroupMaximum modifierGroupMaximum or {@code null} for none
   */
  public StoreMenuItemModifier setModifierGroupMaximum(java.lang.Long modifierGroupMaximum) {
    this.modifierGroupMaximum = modifierGroupMaximum;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifierGroupMinimum() {
    return modifierGroupMinimum;
  }

  /**
   * @param modifierGroupMinimum modifierGroupMinimum or {@code null} for none
   */
  public StoreMenuItemModifier setModifierGroupMinimum(java.lang.Long modifierGroupMinimum) {
    this.modifierGroupMinimum = modifierGroupMinimum;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifierGroupPOSId() {
    return modifierGroupPOSId;
  }

  /**
   * @param modifierGroupPOSId modifierGroupPOSId or {@code null} for none
   */
  public StoreMenuItemModifier setModifierGroupPOSId(java.lang.Long modifierGroupPOSId) {
    this.modifierGroupPOSId = modifierGroupPOSId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModifierGroupShortDescription() {
    return modifierGroupShortDescription;
  }

  /**
   * @param modifierGroupShortDescription modifierGroupShortDescription or {@code null} for none
   */
  public StoreMenuItemModifier setModifierGroupShortDescription(java.lang.String modifierGroupShortDescription) {
    this.modifierGroupShortDescription = modifierGroupShortDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifierPOSId() {
    return modifierPOSId;
  }

  /**
   * @param modifierPOSId modifierPOSId or {@code null} for none
   */
  public StoreMenuItemModifier setModifierPOSId(java.lang.Long modifierPOSId) {
    this.modifierPOSId = modifierPOSId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPrice() {
    return price;
  }

  /**
   * @param price price or {@code null} for none
   */
  public StoreMenuItemModifier setPrice(java.lang.Long price) {
    this.price = price;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getShortDescription() {
    return shortDescription;
  }

  /**
   * @param shortDescription shortDescription or {@code null} for none
   */
  public StoreMenuItemModifier setShortDescription(java.lang.String shortDescription) {
    this.shortDescription = shortDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * @param storeId storeId or {@code null} for none
   */
  public StoreMenuItemModifier setStoreId(java.lang.Long storeId) {
    this.storeId = storeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getWeighting() {
    return weighting;
  }

  /**
   * @param weighting weighting or {@code null} for none
   */
  public StoreMenuItemModifier setWeighting(java.lang.Long weighting) {
    this.weighting = weighting;
    return this;
  }

  @Override
  public StoreMenuItemModifier set(String fieldName, Object value) {
    return (StoreMenuItemModifier) super.set(fieldName, value);
  }

  @Override
  public StoreMenuItemModifier clone() {
    return (StoreMenuItemModifier) super.clone();
  }

}
