/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-13 at 23:14:10 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for StoreMenuCombined.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreMenuCombined extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<StoreMenuHierarchy> storeMenuHierarchy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<StoreMenuItem> storeMenuItem;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<StoreMenuItemModifier> storeMenuItemModifier;

  static {
    // hack to force ProGuard to consider StoreMenuItemModifier used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(StoreMenuItemModifier.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<StoreMenuItemModifierGroup> storeMenuItemModifierGroup;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * @param storeId storeId or {@code null} for none
   */
  public StoreMenuCombined setStoreId(java.lang.Long storeId) {
    this.storeId = storeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<StoreMenuHierarchy> getStoreMenuHierarchy() {
    return storeMenuHierarchy;
  }

  /**
   * @param storeMenuHierarchy storeMenuHierarchy or {@code null} for none
   */
  public StoreMenuCombined setStoreMenuHierarchy(java.util.List<StoreMenuHierarchy> storeMenuHierarchy) {
    this.storeMenuHierarchy = storeMenuHierarchy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<StoreMenuItem> getStoreMenuItem() {
    return storeMenuItem;
  }

  /**
   * @param storeMenuItem storeMenuItem or {@code null} for none
   */
  public StoreMenuCombined setStoreMenuItem(java.util.List<StoreMenuItem> storeMenuItem) {
    this.storeMenuItem = storeMenuItem;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<StoreMenuItemModifier> getStoreMenuItemModifier() {
    return storeMenuItemModifier;
  }

  /**
   * @param storeMenuItemModifier storeMenuItemModifier or {@code null} for none
   */
  public StoreMenuCombined setStoreMenuItemModifier(java.util.List<StoreMenuItemModifier> storeMenuItemModifier) {
    this.storeMenuItemModifier = storeMenuItemModifier;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<StoreMenuItemModifierGroup> getStoreMenuItemModifierGroup() {
    return storeMenuItemModifierGroup;
  }

  /**
   * @param storeMenuItemModifierGroup storeMenuItemModifierGroup or {@code null} for none
   */
  public StoreMenuCombined setStoreMenuItemModifierGroup(java.util.List<StoreMenuItemModifierGroup> storeMenuItemModifierGroup) {
    this.storeMenuItemModifierGroup = storeMenuItemModifierGroup;
    return this;
  }

  @Override
  public StoreMenuCombined set(String fieldName, Object value) {
    return (StoreMenuCombined) super.set(fieldName, value);
  }

  @Override
  public StoreMenuCombined clone() {
    return (StoreMenuCombined) super.clone();
  }

}
