/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-09 at 02:30:03 UTC 
 * Modify at your own risk.
 */

package com.asaan.server.com.asaan.server.endpoint.storeendpoint.model;

/**
 * Model definition for StoreWaitListQueue.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreWaitListQueue extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long dateNotifiedAcknowledged;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long dateNotifiedTableIsReady;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean entryFromInternet;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer estTimeMax;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer estTimeMin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean estimateChangedByStore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long modifiedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer partySize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long storeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String storeName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userObjectId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userPhone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userProfilePhotoUrl;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedDate() {
    return createdDate;
  }

  /**
   * @param createdDate createdDate or {@code null} for none
   */
  public StoreWaitListQueue setCreatedDate(java.lang.Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getDateNotifiedAcknowledged() {
    return dateNotifiedAcknowledged;
  }

  /**
   * @param dateNotifiedAcknowledged dateNotifiedAcknowledged or {@code null} for none
   */
  public StoreWaitListQueue setDateNotifiedAcknowledged(java.lang.Long dateNotifiedAcknowledged) {
    this.dateNotifiedAcknowledged = dateNotifiedAcknowledged;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getDateNotifiedTableIsReady() {
    return dateNotifiedTableIsReady;
  }

  /**
   * @param dateNotifiedTableIsReady dateNotifiedTableIsReady or {@code null} for none
   */
  public StoreWaitListQueue setDateNotifiedTableIsReady(java.lang.Long dateNotifiedTableIsReady) {
    this.dateNotifiedTableIsReady = dateNotifiedTableIsReady;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getEntryFromInternet() {
    return entryFromInternet;
  }

  /**
   * @param entryFromInternet entryFromInternet or {@code null} for none
   */
  public StoreWaitListQueue setEntryFromInternet(java.lang.Boolean entryFromInternet) {
    this.entryFromInternet = entryFromInternet;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getEstTimeMax() {
    return estTimeMax;
  }

  /**
   * @param estTimeMax estTimeMax or {@code null} for none
   */
  public StoreWaitListQueue setEstTimeMax(java.lang.Integer estTimeMax) {
    this.estTimeMax = estTimeMax;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getEstTimeMin() {
    return estTimeMin;
  }

  /**
   * @param estTimeMin estTimeMin or {@code null} for none
   */
  public StoreWaitListQueue setEstTimeMin(java.lang.Integer estTimeMin) {
    this.estTimeMin = estTimeMin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getEstimateChangedByStore() {
    return estimateChangedByStore;
  }

  /**
   * @param estimateChangedByStore estimateChangedByStore or {@code null} for none
   */
  public StoreWaitListQueue setEstimateChangedByStore(java.lang.Boolean estimateChangedByStore) {
    this.estimateChangedByStore = estimateChangedByStore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public StoreWaitListQueue setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getModifiedDate() {
    return modifiedDate;
  }

  /**
   * @param modifiedDate modifiedDate or {@code null} for none
   */
  public StoreWaitListQueue setModifiedDate(java.lang.Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPartySize() {
    return partySize;
  }

  /**
   * @param partySize partySize or {@code null} for none
   */
  public StoreWaitListQueue setPartySize(java.lang.Integer partySize) {
    this.partySize = partySize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public StoreWaitListQueue setStatus(java.lang.Integer status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * @param storeId storeId or {@code null} for none
   */
  public StoreWaitListQueue setStoreId(java.lang.Long storeId) {
    this.storeId = storeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStoreName() {
    return storeName;
  }

  /**
   * @param storeName storeName or {@code null} for none
   */
  public StoreWaitListQueue setStoreName(java.lang.String storeName) {
    this.storeName = storeName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public StoreWaitListQueue setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public StoreWaitListQueue setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserObjectId() {
    return userObjectId;
  }

  /**
   * @param userObjectId userObjectId or {@code null} for none
   */
  public StoreWaitListQueue setUserObjectId(java.lang.String userObjectId) {
    this.userObjectId = userObjectId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserPhone() {
    return userPhone;
  }

  /**
   * @param userPhone userPhone or {@code null} for none
   */
  public StoreWaitListQueue setUserPhone(java.lang.String userPhone) {
    this.userPhone = userPhone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserProfilePhotoUrl() {
    return userProfilePhotoUrl;
  }

  /**
   * @param userProfilePhotoUrl userProfilePhotoUrl or {@code null} for none
   */
  public StoreWaitListQueue setUserProfilePhotoUrl(java.lang.String userProfilePhotoUrl) {
    this.userProfilePhotoUrl = userProfilePhotoUrl;
    return this;
  }

  @Override
  public StoreWaitListQueue set(String fieldName, Object value) {
    return (StoreWaitListQueue) super.set(fieldName, value);
  }

  @Override
  public StoreWaitListQueue clone() {
    return (StoreWaitListQueue) super.clone();
  }

}
