package asaan.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import asaan.dao.AddItem;
import asaan.dao.ModItem;
import asaan.dao.DStore;
import asaan.dao.Trophies;

import asaan.dao.AddItemDao;
import asaan.dao.ModItemDao;
import asaan.dao.DStoreDao;
import asaan.dao.TrophiesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig addItemDaoConfig;
	private final DaoConfig modItemDaoConfig;
	private final DaoConfig dStoreDaoConfig;
	private final DaoConfig trophiesDaoConfig;

	private final AddItemDao addItemDao;
	private final ModItemDao modItemDao;
	private final DStoreDao dStoreDao;
	private final TrophiesDao trophiesDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);

		addItemDaoConfig = daoConfigMap.get(AddItemDao.class).clone();
		addItemDaoConfig.initIdentityScope(type);

		modItemDaoConfig = daoConfigMap.get(ModItemDao.class).clone();
		modItemDaoConfig.initIdentityScope(type);

		dStoreDaoConfig = daoConfigMap.get(DStoreDao.class).clone();
		dStoreDaoConfig.initIdentityScope(type);

		trophiesDaoConfig = daoConfigMap.get(TrophiesDao.class).clone();
		trophiesDaoConfig.initIdentityScope(type);

		addItemDao = new AddItemDao(addItemDaoConfig, this);
		modItemDao = new ModItemDao(modItemDaoConfig, this);
		dStoreDao = new DStoreDao(dStoreDaoConfig, this);
		trophiesDao = new TrophiesDao(trophiesDaoConfig, this);

		registerDao(AddItem.class, addItemDao);
		registerDao(ModItem.class, modItemDao);
		registerDao(DStore.class, dStoreDao);
		registerDao(Trophies.class, trophiesDao);
	}

	public void clear() {
		addItemDaoConfig.getIdentityScope().clear();
		modItemDaoConfig.getIdentityScope().clear();
		dStoreDaoConfig.getIdentityScope().clear();
		trophiesDaoConfig.getIdentityScope().clear();
	}

	public AddItemDao getAddItemDao() {
		return addItemDao;
	}

	public ModItemDao getModItemDao() {
		return modItemDao;
	}

	public DStoreDao getDStoreDao() {
		return dStoreDao;
	}

	public TrophiesDao getTrophiesDao() {
		return trophiesDao;
	}

}
