package asaan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MENU_AND_SUBMENU.
 */
public class MenuAndSubmenu {

    private Boolean active;
    private Long createdDate;
    private String hours;
    private Long id;
    private Integer level;
    private Integer menuItemCount;
    private Integer menuItemPosition;
    private Integer menuType;
    private Long modifiedDate;
    private String name;

    public MenuAndSubmenu() {
    }

    public MenuAndSubmenu(Boolean active, Long createdDate, String hours, Long id, Integer level, Integer menuItemCount, Integer menuItemPosition, Integer menuType, Long modifiedDate, String name) {
        this.active = active;
        this.createdDate = createdDate;
        this.hours = hours;
        this.id = id;
        this.level = level;
        this.menuItemCount = menuItemCount;
        this.menuItemPosition = menuItemPosition;
        this.menuType = menuType;
        this.modifiedDate = modifiedDate;
        this.name = name;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Long getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Long createdDate) {
        this.createdDate = createdDate;
    }

    public String getHours() {
        return hours;
    }

    public void setHours(String hours) {
        this.hours = hours;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getMenuItemCount() {
        return menuItemCount;
    }

    public void setMenuItemCount(Integer menuItemCount) {
        this.menuItemCount = menuItemCount;
    }

    public Integer getMenuItemPosition() {
        return menuItemPosition;
    }

    public void setMenuItemPosition(Integer menuItemPosition) {
        this.menuItemPosition = menuItemPosition;
    }

    public Integer getMenuType() {
        return menuType;
    }

    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    public Long getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(Long modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
