package asaan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TROPHIES.
 */
public class Trophies {

	/** Not-null value. */
	private String name;
	private Long store_id;

	public Trophies() {
	}

	public Trophies(String name, Long store_id) {
		this.name = name;
		this.store_id = store_id;
	}

	/** Not-null value. */
	public String getName() {
		return name;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setName(String name) {
		this.name = name;
	}

	public Long getStore_id() {
		return store_id;
	}

	public void setStore_id(Long store_id) {
		this.store_id = store_id;
	}

}
